#define _POSIX_C_SOURCE 200809L
#include "std.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <math.h>
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

const char std_catalog_identity[] = STD_CATALOG_ID;
const char STD_ABI_SYMBOL = 0;
uint8_t *std_core_status_text(int32_t code) {
    static const char *const names[] = STD_STATUS_NAMES;
    return (uint8_t *)(code >= 0 && code <= STD_LIMIT ? names[code] : "unknown status");
}
int32_t std_core_allocate(uint64_t count, uint64_t size, void **out) {
    if (!out || !size) return STD_INVALID;
    if (count > INT64_MAX / size) return STD_RANGE;
    size_t bytes = (size_t)(count * size);
    void *p = calloc(bytes ? bytes : 1, 1);
    if (!p) return STD_NOMEM;
    memcpy(out, &p, sizeof(p));
    return STD_OK;
}
void std_core_release(void *p) { free(p); }
int32_t std_core_grow(void **data, uint64_t *capacity, uint64_t need, uint64_t width) {
    if (!data || !capacity || !width) return STD_INVALID;
    if (need > INT64_MAX / width) return STD_RANGE;
    if (need <= *capacity) return STD_OK;
    uint64_t n = *capacity ? *capacity : STD_INITIAL_CAPACITY;
    while (n < need) {
        if (n > (uint64_t)INT64_MAX / width / 2) { n = need; break; }
        n *= 2;
    }
    if (n > (uint64_t)INT64_MAX / width) n = need;
    void *base;
    memcpy(&base, data, sizeof(base));
    void *p = realloc(base, (size_t)(n * width));
    if (!p) return STD_NOMEM;
    memcpy(data, &p, sizeof(p)); *capacity = n;
    return STD_OK;
}
uint64_t std_core_initial_capacity(void) { return STD_INITIAL_CAPACITY; }
uint64_t std_core_json_depth(void) { return STD_JSON_DEPTH; }
uint64_t std_core_json_nodes(void) { return STD_JSON_NODES; }
uint64_t std_core_file_limit(void) { return STD_FILE_LIMIT; }
uint64_t std_core_random_zero_seed(void) { return STD_RANDOM_ZERO_SEED; }

double std_math_sqrt(double x) { return sqrt(x); }
double std_math_sin(double x) { return sin(x); }
double std_math_cos(double x) { return cos(x); }
double std_math_log(double x) { return log(x); }
double std_math_exp(double x) { return exp(x); }
double std_math_pow(double x, double y) { return pow(x, y); }
double std_math_floor(double x) { return floor(x); }
double std_math_ceil(double x) { return ceil(x); }

int32_t std_io_open(uint8_t *path, uint64_t len, int32_t mode, StdFile **out) {
    if (!out || !path || !len || len > INT64_MAX - 1 || mode < 0 || mode > 2) return STD_INVALID;
    if (memchr(path, 0, (size_t)len)) return STD_INVALID;
    char *name = NULL; StdFile *file = NULL;
    int32_t status = std_core_allocate(len + 1, 1, (void **)&name);
    if (status) return status;
    memcpy(name, path, (size_t)len);
    status = std_core_allocate(1, sizeof(*file), (void **)&file);
    if (status) { free(name); return status; }
    int flags = O_CLOEXEC | (mode == 0 ? O_RDONLY : O_WRONLY | O_CREAT | (mode == 1 ? O_TRUNC : O_APPEND));
    do { file->fd = open(name, flags, 0666); } while (file->fd < 0 && errno == EINTR);
    free(name);
    if (file->fd < 0) { free(file); return STD_IO; }
    *out = file; return STD_OK;
}
int32_t std_io_close(StdFile *file) {
    if (!file) return STD_OK;
    int result = close(file->fd);
    free(file);
    return result ? STD_IO : STD_OK;
}
int32_t std_io_read(StdFile *file, uint8_t *data, uint64_t capacity, uint64_t *count) {
    if (!file || !count || (capacity && !data)) return STD_INVALID;
    if (capacity > INT64_MAX) return STD_RANGE;
    if (!capacity) { *count = 0; return STD_OK; }
    ssize_t n;
    do { n = read(file->fd, data, (size_t)capacity); } while (n < 0 && errno == EINTR);
    if (n < 0) return STD_IO;
    *count = (uint64_t)n;
    return n ? STD_OK : STD_EOF;
}
int32_t std_io_write(StdFile *file, uint8_t *data, uint64_t len, uint64_t *count) {
    if (!file || !count || (len && !data)) return STD_INVALID;
    if (len > INT64_MAX) return STD_RANGE;
    *count = 0;
    sigset_t blocked, previous, pending;
    sigemptyset(&blocked); sigaddset(&blocked, SIGPIPE);
    if (sigprocmask(SIG_BLOCK, &blocked, &previous)) return STD_IO;
    if (sigpending(&pending)) { sigprocmask(SIG_SETMASK, &previous, NULL); return STD_IO; }
    int result = STD_OK;
    while (*count < len) {
        ssize_t n = write(file->fd, data + *count, (size_t)(len - *count));
        if (n < 0 && errno == EINTR) continue;
        if (n <= 0) {
            // Consume only a SIGPIPE generated by this call, preserving host state.
            if (n < 0 && errno == EPIPE && !sigismember(&pending, SIGPIPE)) {
                struct timespec zero = {0, 0};
                while (sigtimedwait(&blocked, NULL, &zero) < 0 && errno == EINTR) {}
            }
            result = STD_IO;
            break;
        }
        *count += (uint64_t)n;
    }
    if (sigprocmask(SIG_SETMASK, &previous, NULL)) result = STD_IO;
    return result;
}
int32_t std_io_stdout(uint8_t *data, uint64_t len) { StdFile f = {1}; uint64_t n; return std_io_write(&f,data,len,&n); }
int32_t std_io_stderr(uint8_t *data, uint64_t len) { StdFile f = {2}; uint64_t n; return std_io_write(&f,data,len,&n); }

int32_t std_time_monotonic(uint64_t *out) {
    if (!out) return STD_INVALID;
    struct timespec ts;
    if (clock_gettime(CLOCK_MONOTONIC, &ts)) return STD_IO;
    if (ts.tv_sec < 0 || (uint64_t)ts.tv_sec > (UINT64_MAX - (uint64_t)ts.tv_nsec) / 1000000000) return STD_RANGE;
    *out = (uint64_t)ts.tv_sec * 1000000000 + (uint64_t)ts.tv_nsec;
    return STD_OK;
}
int32_t std_time_unix(int64_t *out) {
    if (!out) return STD_INVALID;
    struct timespec ts;
    if (clock_gettime(CLOCK_REALTIME, &ts)) return STD_IO;
    __int128 n = (__int128)ts.tv_sec * 1000000000 + ts.tv_nsec;
    if (n < INT64_MIN || n > INT64_MAX) return STD_RANGE;
    *out = (int64_t)n; return STD_OK;
}
int32_t std_time_sleep(uint64_t n) {
    struct timespec ts = {(time_t)(n / 1000000000), (long)(n % 1000000000)};
    while (nanosleep(&ts, &ts)) if (errno != EINTR) return STD_IO;
    return STD_OK;
}
